name: Sync Subtree
on: push
permissions: write-all

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
          - name: Git Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - name: Git
            run: |
                git subtree --prefix Calculator ${{secrets.DEPLOY_KEY}} main