name: Sync Subtree
on: workflow_dispatch
permissions: write-all

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
          - name: Git Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - uses: nxtlvlsoftware/git-subtree-action@1.1
            with:
              repo: 'LouisCoutel/Calculator'
              path: 'Calculator'
              deploy_key: ${{ secrets.DEPLOY_KEY }}
              branch: main