name: Sync Subtree
on: push
jobs:
    sync:

        runs-on: ubuntu-latest

        steps:
          - name: Git Checkout
            uses: actions/checkout@v2

          - name: Git
            run : |
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"
                git subtree push --prefix Calculator ${{ secrets.DEPLOY_KEY }} main